2021-11-03 16:26:24,323 - instagram_scraper.app - INFO - Saving metadata general information on fritzhansen.json
2021-11-03 16:26:29,498 - instagram_scraper.app - DEBUG - Exception in worker thread
Traceback (most recent call last):
  File "c:\users\lenovo\desktop\scrapers\scraper_env\lib\site-packages\instagram_scraper\app.py", line 451, in worker_wrapper
    return fn(*args, **kwargs)
  File "c:\users\lenovo\desktop\scrapers\scraper_env\lib\site-packages\instagram_scraper\app.py", line 1149, in download
    os.rename(part_file, file_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: './fritzhansen\\251542250_2974799839438963_5088154483579555155_n.jpg.part' -> './fritzhansen\\251542250_2974799839438963_5088154483579555155_n.jpg'
2021-11-03 16:26:29,650 - instagram_scraper.app - DEBUG - Exception in worker thread
Traceback (most recent call last):
  File "c:\users\lenovo\desktop\scrapers\scraper_env\lib\site-packages\instagram_scraper\app.py", line 451, in worker_wrapper
    return fn(*args, **kwargs)
  File "c:\users\lenovo\desktop\scrapers\scraper_env\lib\site-packages\instagram_scraper\app.py", line 1149, in download
    os.rename(part_file, file_path)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: './fritzhansen\\251401361_313724887107887_857901162681414743_n.jpg.part' -> './fritzhansen\\251401361_313724887107887_857901162681414743_n.jpg'
2021-11-03 16:27:44,407 - instagram_scraper.app - ERROR - Media at ['https://instagram.fcrk4-1.fna.fbcdn.net/v/t51.2885-15/e35/p1080x1080/251401361_313724887107887_857901162681414743_n.jpg?_nc_ht=instagram.fcrk4-1.fna.fbcdn.net&_nc_cat=111&_nc_ohc=Iy6Ti3qa4XYAX_fHz0h&edm=AHlfZHwBAAAA&ccb=7-4&oh=f1ccc2275e463207fd7057002c3903b2&oe=6184C859&_nc_sid=21929d&ig_cache_key=MjY5ODA0OTM5NzgwNTA3OTczNw%3D%3D.2-ccb7-4'] generated an exception: [WinError 32] The process cannot access the file because it is being used by another process: './fritzhansen\\251401361_313724887107887_857901162681414743_n.jpg.part' -> './fritzhansen\\251401361_313724887107887_857901162681414743_n.jpg'
2021-11-03 16:27:44,410 - instagram_scraper.app - ERROR - Media at ['https://instagram.fcrk4-1.fna.fbcdn.net/v/t51.2885-15/e35/p1080x1080/251542250_2974799839438963_5088154483579555155_n.jpg?_nc_ht=instagram.fcrk4-1.fna.fbcdn.net&_nc_cat=107&_nc_ohc=2zN-USsqUnUAX8VBCpQ&edm=AHlfZHwBAAAA&ccb=7-4&oh=41b11d76a3f1c48084a524b291f20d53&oe=6184E87A&_nc_sid=21929d&ig_cache_key=MjY5ODA0OTM4MjExODM4OTI0MQ%3D%3D.2-ccb7-4'] generated an exception: [WinError 32] The process cannot access the file because it is being used by another process: './fritzhansen\\251542250_2974799839438963_5088154483579555155_n.jpg.part' -> './fritzhansen\\251542250_2974799839438963_5088154483579555155_n.jpg'
